### ISSUE TITLE
Loop when trying to delete backup

### ISSUE THREAD

**Issue by BasselArt** [spatie/nova-backup-tool#63] opened 2019-10-10 06:24 UTC
**Hello,**

**Thanks for the great tool!**

When I trying to delete any backup the action box disappears and appears every 1 second.
Attached GIF to describe this issue:
![Issue GIF](https://user-images.githubusercontent.com/5476744/66543955-76328480-eb3f-11e9-952a-349ece4a38a4.gif)

**Comment by schonhoff** [comment] 2019-10-10 14:04
Hi,

i have the same issue. I'm on Nova 2.4 and Laravel 6.
I can't even see the dialog.
The Health Check is the root cause. Every time it checks for the health status it refreshes the site. 

Hopefully that helps to find the error.

**Comment by freekmurze** [comment] 2019-10-10 22:47
I'd accept a PR that fixes this.

**Comment by philipbaginski** [comment] 2020-01-23 10:03
I have the same issue. Any help?

**Comment by pschepat** [comment] 2020-01-26 22:28
Same issue here. Also it's not working with AWS SQS... If I use SQS as queue driver the tool doesn't create a backup file. In the dev-console no errors.  I tested the driver with a separate job that works properly.

**Comment by ragingdave** [comment] 2020-02-13 18:27
I didn't realize it, but this is basically #73 that I just put in

**Comment by freekmurze** [comment] 2020-02-14 08:09
Closing this as #73 describers the problem better.

**Closed by freekmurze** 2020-02-14 08:09 UTC

**Comment by OthmanAlseagh** [comment] 2021-03-21 09:59
@freekmurze i have this issue also
        "spatie/nova-backup-tool": "4.1.2",
        "spatie/laravel-backup": "6.15.1",
