### ISSUE TITLE
Not install because spatie/nova-backup-tool 3.5.0 requires laravel/nova ^2.0... But i have laravel nova 2.3.0

### ISSUE THREAD

**Issue by wemersonrv** [spatie/nova-backup-tool#62] opened 2019-10-09 13:53 UTC
Hi, when try to install in laravel nova v2.3.0 it gives me an `matching package found`  for laravel nova.

Obs:
* First: I have laravel nova, v2.3.0 installed so it's greather than `^2.0`
* Second: I have two laravel nova licenses, and in the first project nova-backup-tool install fine, and the other one not works... but both `composer.json` has the same laravel-nova version...

```bash
$ composer require spatie/nova-backup-to ol
Using version ^3.5 for spatie/nova-backup-tool
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/nova-backup-tool ^3.5 -> satisfiable by spatie/nova-backup-tool[3.5.0].
    - spatie/nova-backup-tool 3.5.0 requires laravel/nova ^2.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by wemersonrv** [comment] 2019-10-14 16:00
Hello. Any light here?! how can i solve this problem to install the package!?!?!?!

**Comment by freekmurze** [comment] 2019-10-14 23:51
I cannot recreate this problem, seems to be working fine.

It must be something in your project. Have you tried installing it in a fresh Laravel app?

**Comment by wemersonrv** [comment] 2019-10-15 17:05
> I cannot recreate this problem, seems to be working fine.
> 
> It must be something in your project. Have you tried installing it in a fresh Laravel app?

Yes, try in a clean new project and works... So i've remove the `vendor` folder and `composer.lock` in the proejct that not works and try again... And **not works too**... same problem.

So i've remove all laravel nova packages, lefting only nova... and try again... and not works too!!! same message..

**Comment by wemersonrv** [comment] 2019-10-28 12:06
Hello. Updating the issue!

All these problems happens when use Laravel Nova as a local repository (zip file). When i change it to nova remote private repository all stuffs works.

So the problem is with nova, not this amazing package!

**Comment by freekmurze** [comment] 2019-10-29 03:42
Closing this, because the problem is probably not caused by this package.

**Closed by freekmurze** 2019-10-29 03:42 UTC
